### ISSUE TITLE
Suggestions about AI Attack

### ISSUE THREAD

**Issue by bck6d03** [min2222/Super-Duper-Ultra-Hyper-Tamer#6]
Current: 
- tamed mob always target to mob of Owner attack. So every time the player attack, the attack target of tamed mobs will be changed.

Suggestion:
- Make a "control tool" for player to control tamed mob
  - right click:
     - if looking at non tame mob: make all "following" tamed mob attack the target mob.
     - if looking at block: make all "following" tamed mob moves to looking block position first.
  - shift + right click:
     - default: teleport all "following" tamed mob to Owner.
     - if looking at tamed mob: change "attack mode" of tamed mob
       - [Hunting Mode]: Actively attack untamed hostile monsters in "attackRange". 
       - [Passive Mode]: Attack the mob of Owner attack. Or Owner be attacking. just like vanilla wolf.
       - [Peaceful Mode]: Stop all aggressive behavior. 
- When a tamed mob already has an attack target, they will not change targets. Unless the player uses the "control tool"

BUG：
- "teleportRange" not working when tamed mobs have attack target.

**Comment by min2222** [comment]
teleport range only work when mob is in following state.
i'll also make it doesn't change target when already have target

**Comment by bck6d03** [comment]
Unfortunately, I just found out in the "following state" that it doesn't work when tamed mobs have attack target. This makes my pet refuse to run away from a fight and fight to the death. 
I proposed the "control tool" also to prevent uncontrolled battles of tamed mobs.

**Comment by min2222** [comment]
yeah because they only following if target is outside "attackRange" config option
